"""empty message

Revision ID: 17b55637d877
Revises: e3100bb2b082
Create Date: 2023-08-17 16:41:28.862633

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '17b55637d877'
down_revision = 'e3100bb2b082'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_collaborator_id', table_name='collaborator')
    op.drop_table('collaborator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('note_id', sa.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('is_update', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['note_id'], ['note.id'], name='collaborator_note_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='collaborator_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='collaborator_pkey')
    )
    op.create_index('ix_collaborator_id', 'collaborator', ['id'], unique=False)
    # ### end Alembic commands ###
